n = str(input("Digite algo: "))
print(f'O tipo primitivo de {n} é {type(n)}')
print(f'{n} é numérico? {n.isnumeric()}')
print(f'{n} é alfabético? {n.isalpha()}')
print(f'{n} é alfanumérico? {n.isalnum()}')
print(f'{n} está capitalizada? {n.istitle()}')
print(f'{n} só tem espaços? {n.isspace()}')
print(f'{n} está em maiúsculas? {n.isupper()}')
print(f'{n} está em minúsculas? {n.islower()}')
print(f'{n} é printável? {n.isprintable()}')
print(f'{n} é decimal? {n.isdecimal()}')