from classes import BichinhoVirtual

print("\033[1;34m=== BICHINHO 1 ===\033[m")
bicho1 = BichinhoVirtual("Bob", 10, 100, 100)
bicho1.alterar_nome()
bicho1.alterar_idade()
bicho1.alterar_saude()
bicho1.alterar_porcentagem_de_fome()
bicho1.show_info_about()
bicho1.BrincarComBichinho()
bicho1.AlimentarBichinho()
bicho1.calcular_humor()

print("\033[1;34m=== BICHINHO 2 ===\033[m")
bicho2 = BichinhoVirtual("Albert", 4, 90, 80)
bicho2.alterar_nome()
bicho2.alterar_idade()
bicho2.alterar_saude()
bicho2.alterar_porcentagem_de_fome()
bicho2.show_info_about()
bicho2.BrincarComBichinho()
bicho2.AlimentarBichinho()
bicho2.calcular_humor()

print("\033[1;34m=== BICHINHO 3 ===\033[m")
bicho3 = BichinhoVirtual("Frederico", 15, 60, 68)
bicho3.alterar_nome()
bicho3.alterar_idade()
bicho3.alterar_saude()
bicho3.alterar_porcentagem_de_fome()
bicho3.show_info_about()
bicho3.BrincarComBichinho()
bicho3.AlimentarBichinho()
bicho3.calcular_humor()

print("\033[1;34m=== BICHINHO 4 ===\033[m")
bicho4 = BichinhoVirtual("Freddy", 1, 30, 45)
bicho4.alterar_nome()
bicho4.alterar_idade()
bicho4.alterar_saude()
bicho4.alterar_porcentagem_de_fome()
bicho4.show_info_about()
bicho4.BrincarComBichinho()
bicho4.AlimentarBichinho()
bicho4.calcular_humor()

print("\033[1;34m=== BICHINHO 5 ===\033[m")
bicho5 = BichinhoVirtual("Toby", 2, 0, 0)
bicho5.alterar_nome()
bicho5.alterar_idade()
bicho5.alterar_saude()
bicho5.alterar_porcentagem_de_fome()
bicho5.show_info_about()
bicho5.BrincarComBichinho()
bicho5.AlimentarBichinho()
bicho5.calcular_humor()