from arqclasses import Dispositivo, Celular, Computador, Tv, Tablet

pc1 = Computador("DELL", '20"', 'Xeon', "4TB", "64GB")
cel1 = Celular("Xiaomi", '6"', 'Snapdragon 888', "128GB", '8GB')
tv1 = Tv("LG", '50"', 'Xeon', '1GB', '4Gb')
tb1 = Tablet("Lenovo", '')
print(pc1.marca, pc1.tamanho_tela, pc1.cpu, pc1.disco, pc1.ram)
pc1.teclar("ENTER")
pc1.mousear("browser")
pc1.ligar()
pc1.desligar()
print(cel1.marca, cel1.tamanho_tela, cel1.cpu, cel1.disco, cel1.ram)
cel1.teclar("a")
cel1.tirar_foto()
cel1.ligar()
cel1.desligar()
tv1.ligar()
tv1.desligar()
tv1.mudar_canal(10)